name: Build Infra Artefact

on:
  push:
    branches:
      - "**"
    paths:
      - mariadb
      - odoo
      - postgresql
      - docker-compose.yml
      - Makefile
      - .github/workflows/artifact-init.yaml
  workflow_dispatch:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-package

      - name: test
        run: |
          echo "ok";
          ls -alt
          
jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: |
            mariadb
            odoo
            postgresql
            docker-compose.yml
            Makefile
            .github/workflows/artifact-init.yaml

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-package

      - name: test
        run: |
          echo "ok";
          ls -alt
