name: Build Infra Artefact

on:
  push:
    branches:
      - "**"
    paths:
      - mariadb
      - odoo
      - postgresql
      - docker-compose.yml
      - Makefile
      - .github/workflows/artifact-init.yaml

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: |
            mariadb
            odoo
            postgresql
            docker-compose.yml
            Makefile
            .github/workflows/artifact-init.yaml

