name: Build Flask Dev

on:
  push:
    branches:
      - "**"
    paths:
      - app/flask/app/**
      - .github/workflows/build-flask-dev.yaml

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    environment: "flask - dev"
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo ${{ github.ref_name }};
          echo "VERSION=$(date "+%Y%m%d.%H%M%S").${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GHCR_REPOSITORY=deuky/chift-api-flask" >> $GITHUB_ENV
          REF_NAME="${{ github.ref_name }}"
          REF_NAME="${REF_NAME,,}"
          echo "REF_NAME=${REF_NAME/\//-}" >> $GITHUB_ENV
          make _models;
          make _database;

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app/flask
          build-args: |
            BASE_REF=${{ vars.BASE_REF }}
          target: unit
          file: ./app/flask/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_REPOSITORY }}:${{ env.REF_NAME }}-${{ env.VERSION }}

