name: Update Instance

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    environment: "gustin.page"

    steps:
      - name: Deploy & Install via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: chift-api.gustin.page
          username: root
          key: ${{ secrets.DEPLOY_SSH }}
          script: |
            cd /media/chift-api
            docker compose pull -f
            docker compose up -d
