name: Commit Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "VERSION=$(date "+%Y%m%d.%H%M%S").${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GHCR_REPOSITORY=deuky/chift-api" >> $GITHUB_ENV
          make _models;
          make _database;

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image Flask
        uses: docker/build-push-action@v5
        with:
          context: ./app/flask
          target: prod
          file: ./app/flask/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_REPOSITORY }}-flask:${{ env.VERSION }}

      - name: Build and push Docker image Django
        uses: docker/build-push-action@v5
        with:
          context: ./app/django
          target: prod
          file: ./app/django/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_REPOSITORY }}-django:${{ env.VERSION }}

      - name: Build and push Docker image FastAPI
        uses: docker/build-push-action@v5
        with:
          context: ./app/fastapi
          target: prod
          file: ./app/fastapi/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_REPOSITORY }}-fastapi:${{ env.VERSION }}