name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: |
            mariadb
            odoo
            postgresql
            docker-compose.yml
            Makefile
            .github/workflows/artifact-init.yaml

  deploy:
    name: Deploy (manual only)
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: "gustin.page"

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-package

      - name: Upload artifact to server (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: chift-api.gustin.page
          username: root
          key: ${{ secrets.DEPLOY_SSH }}
          source: ./
          target: /media/chift-api

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: chift-api.gustin.page
          username: root
          key: ${{ secrets.DEPLOY_SSH }}
          script: |
            cd /media/chift-api
            ls -lat